web:
  dockerfile: Dockerfile
  build: ./docker/nginx
  links:
    - php
  ports:
    - 80:80
  volumes:
    - .:/var/www/html
php:
  dockerfile: Dockerfile
  build: ./docker/php
  links:
    - pg
    - redis
  volumes:
    - .:/var/www/html
pg:
  dockerfile: Dockerfile
  build: ./docker/pg
  ports:
    - 5432:5432
  env_file: .env
redis:
  dockerfile: Dockerfile
  build: ./docker/redis
  ports:
    - 6379:6379
